spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: secretpassword123
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
custom:
  keycloak:
    uri: http://localhost:8080/realms/develop
    client-id: login-app
    username: notification_service
    password: 1
server:
  port: 8083